version: '2.0'

services:
  nginx:
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - 8001:80
    volumes:
      - ./log:/var/log/nginx
      - ./www:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./vhosts:/etc/nginx/vhosts
      - /etc/letsencrypt:/etc/letsencrypt
