!!com.easynas.server.model.AdminConfig
fileSavePaths:
  master: [/disks/sda1/easy-nas-data/file]
  backup: null
generalInformationPath: {
  master: /disks/sda1/easy-nas-data/general-information/,
  backup: null
}
