version: '2.0'
  
services:
  easy-nas-server:
    restart: unless-stopped
    image: easy-nas/easy-nas-server:0.0.3
    ports:
      - 8888:8888
      - 2222:2222
    volumes:
      - ./admin-config.yml:/usr/share/easy-nas/admin-config.yml
      - ./logs:/usr/share/easy-nas/logs
      - /disks/sda1:/disks/sda1
